plugins {
    id 'application'
    id 'org.graalvm.buildtools.native' version '0.11.1'
}

dependencies {
    implementation project(':core')
    implementation 'com.fasterxml.jackson.core:jackson-core:2.20.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'dev.isksss.java.sqlformatter.cli.SqlFormatterCli'
}

graalvmNative {
    binaries {
        main {
            imageName = 'sql-formatter-java'
        }
    }
}
